# Generated by Django 5.2.6 on 2025-10-01 23:54

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sign_up', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usercontent',
            old_name='content',
            new_name='description',
        ),
        migrations.RemoveField(
            model_name='usercontent',
            name='QrCode',
        ),
        migrations.RemoveField(
            model_name='usercontent',
            name='URL',
        ),
        migrations.RemoveField(
            model_name='usercontent',
            name='image',
        ),
        migrations.RemoveField(
            model_name='usercontent',
            name='video',
        ),
        migrations.AddField(
            model_name='usercontent',
            name='image_path',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='usercontent',
            name='name',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usercontent',
            name='url',
            field=models.URLField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
